### <font color="brown">Pandas - DataFrame Continued</font>

In [1]:
import numpy as np
import pandas as pd
from pandas import Series
from pandas import DataFrame

---

#### <font color="brown">Working with NaNs</font>

#### Remove rows/columns with NaNs using dropna

In [4]:
from numpy import nan as NA
datf = DataFrame([[1, 3.8, 2.1],
                  [2, NA, NA],
                  [NA, NA, NA],
                  [NA, 4.8, 1.7]])
datf

0    1    2
0  1.0  3.8  2.1
1  2.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  4.8  1.7

**Drop rows that have an NaN in any column**

In [5]:
datf.dropna()

0    1    2
0  1.0  3.8  2.1

In [6]:
datf

0    1    2
0  1.0  3.8  2.1
1  2.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  4.8  1.7

**Original is not modified, use inplace=True to modify original**

In [7]:
datf1 = datf.copy()
datf1.dropna(inplace=True)
datf1

0    1    2
0  1.0  3.8  2.1

In [8]:
# to do the same with columns, pass axis=1
datf.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

**To drop only those rows/columns that have NaN in ALL columns**

In [9]:
# drop rows that have NaNs in all columns
datf.dropna(how='all')

0    1    2
0  1.0  3.8  2.1
1  2.0  NaN  NaN
3  NaN  4.8  1.7

In [10]:
# drop columns that have all NaNs
datf.dropna(how='all',axis=1)  # none of the columns are entirely NAs

0    1    2
0  1.0  3.8  2.1
1  2.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  4.8  1.7

#### Filling NaNs with values

**Replace all NaNs with single value**

In [11]:
datf

0    1    2
0  1.0  3.8  2.1
1  2.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  4.8  1.7

In [12]:
datf.fillna(0)

0    1    2
0  1.0  3.8  2.1
1  2.0  0.0  0.0
2  0.0  0.0  0.0
3  0.0  4.8  1.7

**Replace all NaNs in row or column using ffill (forward fill)**

In [13]:
# column-wise
datf.fillna(method='ffill')

0    1    2
0  1.0  3.8  2.1
1  2.0  3.8  2.1
2  2.0  3.8  2.1
3  2.0  4.8  1.7

In [14]:
datf   # original not modified

0    1    2
0  1.0  3.8  2.1
1  2.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  4.8  1.7

In [15]:
# row-wise
datf.fillna(method='ffill',axis=1)

0    1    2
0  1.0  3.8  2.1
1  2.0  2.0  2.0
2  NaN  NaN  NaN
3  NaN  4.8  1.7

**Replace all NaNs in multiple columns using dictionary**

In [16]:
datf

0    1    2
0  1.0  3.8  2.1
1  2.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  4.8  1.7

In [17]:
datf.fillna({1: 2.5, 2: 1.5})  # 2.5 in column 1, 1.5 in column 2

0    1    2
0  1.0  3.8  2.1
1  2.0  2.5  1.5
2  NaN  2.5  1.5
3  NaN  4.8  1.7

In [18]:
datf  # unchanged

0    1    2
0  1.0  3.8  2.1
1  2.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  4.8  1.7

**Treat column/row separately as Series, and use fillna**

In [19]:
# column as Series and fillna
datf[2].fillna(1.5)

0    2.1
1    1.5
2    1.5
3    1.7
Name: 2, dtype: float64

In [20]:
datf  # original unchanged

0    1    2
0  1.0  3.8  2.1
1  2.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  4.8  1.7

In [21]:
# row as Series, and fillna inplace
datfc = datf.copy()
datfc.loc[2].fillna(-1,inplace=True)
datfc

0    1    2
0  1.0  3.8  2.1
1  2.0  NaN  NaN
2 -1.0 -1.0 -1.0
3  NaN  4.8  1.7

---
#### <font color="brown">One way to deal with missing numeric data is to replace with mean</font>

In [22]:
mpgfile = open("auto_mpg_original.csv")
mpgs = pd.read_csv(mpgfile)
mpgs

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0        8.0         307.0       130.0  3504.0          12.0   
1    15.0        8.0         350.0       165.0  3693.0          11.5   
2    18.0        8.0         318.0       150.0  3436.0          11.0   
3    16.0        8.0         304.0       150.0  3433.0          12.0   
4    17.0        8.0         302.0       140.0  3449.0          10.5   
..    ...        ...           ...         ...     ...           ...   
401  27.0        4.0         140.0        86.0  2790.0          15.6   
402  44.0        4.0          97.0        52.0  2130.0          24.6   
403  32.0        4.0         135.0        84.0  2295.0          11.6   
404  28.0        4.0         120.0        79.0  2625.0          18.6   
405  31.0        4.0         119.0        82.0  2720.0          19.4   

     model year  origin                   car name  
0          70.0     1.0  chevrolet chevelle malibu  
1          70.0     1.0          buick skylark 320  
2          70.0     1.0         plymouth satellite  
3          70.0     1.0              amc rebel sst  
4          70.0     1.0                ford torino  
..          ...     ...                        ...  
401        82.0     1.0            ford mustang gl  
402        82.0     2.0                  vw pickup  
403        82.0     1.0              dodge rampage  
404        82.0     1.0                ford ranger  
405        82.0     1.0                 chevy s-10  

[406 rows x 9 columns]

In [23]:
mpgs['mpg'].mean()

23.514572864321607

In [24]:
mpgs2 = mpgs.copy()

In [25]:
mpgs2[mpgs2['mpg'].isnull()]

mpg  cylinders  displacement  horsepower  weight  acceleration  \
10   NaN        4.0         133.0       115.0  3090.0          17.5   
11   NaN        8.0         350.0       165.0  4142.0          11.5   
12   NaN        8.0         351.0       153.0  4034.0          11.0   
13   NaN        8.0         383.0       175.0  4166.0          10.5   
14   NaN        8.0         360.0       175.0  3850.0          11.0   
17   NaN        8.0         302.0       140.0  3353.0           8.0   
39   NaN        4.0          97.0        48.0  1978.0          20.0   
367  NaN        4.0         121.0       110.0  2800.0          15.4   

     model year  origin                          car name  
10         70.0     2.0              citroen ds-21 pallas  
11         70.0     1.0  chevrolet chevelle concours (sw)  
12         70.0     1.0                  ford torino (sw)  
13         70.0     1.0           plymouth satellite (sw)  
14         70.0     1.0                amc rebel sst (sw)  
17         70.0     1.0             ford mustang boss 302  
39         71.0     2.0       volkswagen super beetle 117  
367        81.0     2.0                         saab 900s

##### **Use fillna method on relevant column (Series)**

In [26]:
mpgs2['mpg'] = mpgs2['mpg'].fillna(mpgs2['mpg'].mean())

In [27]:
mpgs2.loc[10:14]

mpg  cylinders  displacement  horsepower  weight  acceleration  \
10  23.514573        4.0         133.0       115.0  3090.0          17.5   
11  23.514573        8.0         350.0       165.0  4142.0          11.5   
12  23.514573        8.0         351.0       153.0  4034.0          11.0   
13  23.514573        8.0         383.0       175.0  4166.0          10.5   
14  23.514573        8.0         360.0       175.0  3850.0          11.0   

    model year  origin                          car name  
10        70.0     2.0              citroen ds-21 pallas  
11        70.0     1.0  chevrolet chevelle concours (sw)  
12        70.0     1.0                  ford torino (sw)  
13        70.0     1.0           plymouth satellite (sw)  
14        70.0     1.0                amc rebel sst (sw)

In [28]:
mpgs[mpgs['horsepower'].isnull()]

mpg  cylinders  displacement  horsepower  weight  acceleration  \
38   25.0        4.0          98.0         NaN  2046.0          19.0   
133  21.0        6.0         200.0         NaN  2875.0          17.0   
337  40.9        4.0          85.0         NaN  1835.0          17.3   
343  23.6        4.0         140.0         NaN  2905.0          14.3   
361  34.5        4.0         100.0         NaN  2320.0          15.8   
382  23.0        4.0         151.0         NaN  3035.0          20.5   

     model year  origin              car name  
38         71.0     1.0            ford pinto  
133        74.0     1.0         ford maverick  
337        80.0     2.0  renault lecar deluxe  
343        80.0     1.0    ford mustang cobra  
361        81.0     2.0           renault 18i  
382        82.0     1.0        amc concord dl

In [29]:
mpgs2['horsepower'] = mpgs2['horsepower'].fillna(mpgs2['horsepower'].mean())

In [30]:
mpgs2.loc[[38,133]]

mpg  cylinders  displacement  horsepower  weight  acceleration  \
38   25.0        4.0          98.0    105.0825  2046.0          19.0   
133  21.0        6.0         200.0    105.0825  2875.0          17.0   

     model year  origin       car name  
38         71.0     1.0     ford pinto  
133        74.0     1.0  ford maverick

In [31]:
mpgs2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 406 entries, 0 to 405
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           406 non-null    float64
 1   cylinders     406 non-null    float64
 2   displacement  406 non-null    float64
 3   horsepower    406 non-null    float64
 4   weight        406 non-null    float64
 5   acceleration  406 non-null    float64
 6   model year    406 non-null    float64
 7   origin        406 non-null    float64
 8   car name      406 non-null    object 
dtypes: float64(8), object(1)
memory usage: 28.7+ KB


**No null values anywhere**

---

#### <font color="brown">General data frame manipulation</font>

**Column returned on indexing is a VIEW, so modifications will affect underlying dataframe column**

In [32]:
rand2d = np.random.random((3,2))
rand2d

array([[0.12745642, 0.23760859],
       [0.81030443, 0.57824097],
       [0.2588027 , 0.15506729]])

In [33]:
randdf = DataFrame(rand2d, index=['one', 'two', 'three'],
                   columns = ['first', 'second'])
randdf

first    second
one    0.127456  0.237609
two    0.810304  0.578241
three  0.258803  0.155067

In [34]:
col2 = randdf['second']
col2

one      0.237609
two      0.578241
three    0.155067
Name: second, dtype: float64

In [35]:
col2 += 0.05
print(col2,'\n')
print(randdf)

one      0.287609
two      0.628241
three    0.205067
Name: second, dtype: float64 

          first    second
one    0.127456  0.287609
two    0.810304  0.628241
three  0.258803  0.205067


In [36]:
# if you don't want this, make an explicit copy of the returned column series
randdf['second'] -= 0.05
randdf

first    second
one    0.127456  0.237609
two    0.810304  0.578241
three  0.258803  0.155067

In [37]:
col2 = randdf['second'].copy()
col2 += 0.05
print(col2,'\n')
print(randdf)

one      0.287609
two      0.628241
three    0.205067
Name: second, dtype: float64 

          first    second
one    0.127456  0.237609
two    0.810304  0.578241
three  0.258803  0.155067


#### Adding dataframes together

In [38]:
rand2d = np.random.random((3,3))
randdf2 = DataFrame(rand2d, index=['one', 'two', 'four'],
                   columns = ['first', 'second', 'third'])
randdf2

first    second     third
one   0.395910  0.539823  0.793462
two   0.561883  0.344290  0.440060
four  0.527717  0.378387  0.137646

In [39]:
randdf

first    second
one    0.127456  0.237609
two    0.810304  0.578241
three  0.258803  0.155067

In [40]:
randdf + randdf2   # NaN will be used if either of a pair of aligned values is missing

first    second  third
four        NaN       NaN    NaN
one    0.523367  0.777431    NaN
three       NaN       NaN    NaN
two    1.372187  0.922531    NaN

**Note that indexes are arranged in lexicographic order**

---

#### <font color="brown">Function Application and Mapping</font>

##### <font color="brown">apply, for Series objects of DataFrame (columns or rows)</font>

In [41]:
df = DataFrame(np.random.randn(4,3),columns=list("ABC"),index=["One","Two","Three",'Four'])
df

A         B         C
One    1.039422 -0.430296  1.470477
Two    0.596558 -3.381094 -0.682264
Three -1.734354  1.091601  0.326652
Four  -0.562562  1.308296 -0.533065

In [42]:
dfabs = df.abs()
dfabs

A         B         C
One    1.039422  0.430296  1.470477
Two    0.596558  3.381094  0.682264
Three  1.734354  1.091601  0.326652
Four   0.562562  1.308296  0.533065

**Function that rounds each item of a series that will be sent as parameter**

In [43]:
roundfn = lambda x: round(x,2)  # x is a Series

**Use apply method on dataframe with function as parameter, each column will be sent as argument to function**

In [45]:
dfabs.apply(roundfn)  # each column is sent in as an argument

A     B     C
One    0.23  0.87  0.42
Two    1.04  0.06  0.86
Three  0.42  1.90  0.55
Four   0.70  0.59  0.80

In [44]:
dfabs  # original does not change

A         B         C
One    1.039422  0.430296  1.470477
Two    0.596558  3.381094  0.682264
Three  1.734354  1.091601  0.326652
Four   0.562562  1.308296  0.533065

In [45]:
# or you can directly write the lambda as argument
dfabs.apply(lambda x: round(x,2))

A     B     C
One    1.04  0.43  1.47
Two    0.60  3.38  0.68
Three  1.73  1.09  0.33
Four   0.56  1.31  0.53

In [46]:
# this makes it clear that apply is executed a column at a time (axis=0 is default)
dfabs.apply(lambda x: np.cumsum(x))

A         B         C
One    1.039422  0.430296  1.470477
Two    1.635980  3.811389  2.152741
Three  3.370334  4.902991  2.479392
Four   3.932895  6.211287  3.012458

In [47]:
# you can define any function, not just lambdas
def roundsum(x):
    return round(np.cumsum(x),2)

In [48]:
dfabs.apply(roundsum)

A     B     C
One    1.04  0.43  1.47
Two    1.64  3.81  2.15
Three  3.37  4.90  2.48
Four   3.93  6.21  3.01

In [49]:
dfabs

A         B         C
One    1.039422  0.430296  1.470477
Two    0.596558  3.381094  0.682264
Three  1.734354  1.091601  0.326652
Four   0.562562  1.308296  0.533065

In [50]:
# a row at a time
dfabs.apply(roundsum,axis=1)

A     B     C
One    1.04  1.47  2.94
Two    0.60  3.98  4.66
Three  1.73  2.83  3.15
Four   0.56  1.87  2.40

In [51]:
# of course, you can simply extract a column or row and send it 
dfabs['A'].apply(roundfn)

One      1.04
Two      0.60
Three    1.73
Four     0.56
Name: A, dtype: float64

In [52]:
# and if you are going to do this, you can use the Series map function
dfabs['B'].map(roundfn)

One      0.43
Two      3.38
Three    1.09
Four     1.31
Name: B, dtype: float64

In [53]:
dfabs  # original not changed

A         B         C
One    1.039422  0.430296  1.470477
Two    0.596558  3.381094  0.682264
Three  1.734354  1.091601  0.326652
Four   0.562562  1.308296  0.533065

In [54]:
dfabs.loc['Two'].apply(roundfn)

A    0.60
B    3.38
C    0.68
Name: Two, dtype: float64

In [55]:
# since round is a Python function you can use it directly
dfabs.loc['Two'].round(2)

A    0.60
B    3.38
C    0.68
Name: Two, dtype: float64

In [59]:
dfabs

A         B         C
One    0.232281  0.870930  0.422691
Two    1.038920  0.062612  0.856530
Three  0.419909  1.898398  0.548260
Four   0.698138  0.590179  0.797566

In [56]:
# for built-in Python functions, apply is generally unnecessary
dfabs.round(2)

A     B     C
One    1.04  0.43  1.47
Two    0.60  3.38  0.68
Three  1.73  1.09  0.33
Four   0.56  1.31  0.53

In [57]:
# try mapping two rows
dfabs.loc[['Two','Three']].map(lambda x: round(x,2))

AttributeError: 'DataFrame' object has no attribute 'map'

In [58]:
# won't work because the indexing gives a dataframe, so use apply
dfabs.loc[['Two','Three']].apply(lambda x: round(x,2))

A     B     C
Two    0.60  3.38  0.68
Three  1.73  1.09  0.33

---

##### <font color="brown">applymap, for one item of a DataFrame at a time</font>

In [59]:
dfabs.applymap(lambda x: round(x,2))  

A     B     C
One    1.04  0.43  1.47
Two    0.60  3.38  0.68
Three  1.73  1.09  0.33
Four   0.56  1.31  0.53

In [60]:
dfabs  # original not changed

A         B         C
One    1.039422  0.430296  1.470477
Two    0.596558  3.381094  0.682264
Three  1.734354  1.091601  0.326652
Four   0.562562  1.308296  0.533065

In [61]:
dfabs.applymap(lambda x: np.round(np.cumsum(x),2))

A       B       C
One    [1.04]  [0.43]  [1.47]
Two     [0.6]  [3.38]  [0.68]
Three  [1.73]  [1.09]  [0.33]
Four   [0.56]  [1.31]  [0.53]

##### **each item is treated like an ndarray, so cumulative sum is trivially done on a single item**

---

#### <font color="brown">Iterating over rows and columns of DataFrame</font>

##### <font color="brown">Iterating over rows using iterrows</font>

In [64]:
dfabs

A         B         C
One    1.039422  0.430296  1.470477
Two    0.596558  3.381094  0.682264
Three  1.734354  1.091601  0.326652
Four   0.562562  1.308296  0.533065

In [65]:
dfround = dfabs.round(2)
dfround

A     B     C
One    1.04  0.43  1.47
Two    0.60  3.38  0.68
Three  1.73  1.09  0.33
Four   0.56  1.31  0.53

In [66]:
for row in dfround.iterrows():
    print(row,'\n')

('One', A    1.04
B    0.43
C    1.47
Name: One, dtype: float64) 

('Two', A    0.60
B    3.38
C    0.68
Name: Two, dtype: float64) 

('Three', A    1.73
B    1.09
C    0.33
Name: Three, dtype: float64) 

('Four', A    0.56
B    1.31
C    0.53
Name: Four, dtype: float64) 



**Each row is returned as a tuple: first item is index label of row, second item is Series for row.<br>
For each row Series, its index are the column names, and values are values in that row**

In [67]:
for row in dfround.iterrows():
    ser = row[1]
    print(ser.index)
    print(ser.values)
    print('\n')

Index(['A', 'B', 'C'], dtype='object')
[1.04 0.43 1.47]


Index(['A', 'B', 'C'], dtype='object')
[0.6  3.38 0.68]


Index(['A', 'B', 'C'], dtype='object')
[1.73 1.09 0.33]


Index(['A', 'B', 'C'], dtype='object')
[0.56 1.31 0.53]




In [68]:
# retrieving column values individually
for row in dfround.iterrows():
    ser = row[1]
    for i,col in enumerate(ser.index):
        print(f'{col}: {ser.values[i]}')
    print('\n')

A: 1.04
B: 0.43
C: 1.47


A: 0.6
B: 3.38
C: 0.68


A: 1.73
B: 1.09
C: 0.33


A: 0.56
B: 1.31
C: 0.53




---

#### <font color="brown">Grouping</font>

##### <font color="brown">Example 1a: State populations by year</font>

In [2]:
popdat = {'state': ['Arizona','Arizona','Arizona','Virginia','Virginia'],
          'year': [2005, 2010, 2015, 2010, 2015],
          'pop': [5.9, 6.6, 6.8, 7.9, 8.3]}
popdf = DataFrame(popdat)
popdf

state  year  pop
0   Arizona  2005  5.9
1   Arizona  2010  6.6
2   Arizona  2015  6.8
3  Virginia  2010  7.9
4  Virginia  2015  8.3

In [3]:
# first group by year
yrgrp = popdf.groupby('year')
yrgrp

In [4]:
# then sum up within each group
df = yrgrp.sum()  # pop is the only numeric column, so sum applies to it
df

state   pop
year                       
2005          Arizona   5.9
2010  ArizonaVirginia  14.5
2015  ArizonaVirginia  15.1

In [5]:
df.index.name

'year'

In [6]:
df.reset_index()  # so we can have year as a column

year            state   pop
0  2005          Arizona   5.9
1  2010  ArizonaVirginia  14.5
2  2015  ArizonaVirginia  15.1

In [7]:
# in one shot
popdf.groupby('year').sum().reset_index()

year            state   pop
0  2005          Arizona   5.9
1  2010  ArizonaVirginia  14.5
2  2015  ArizonaVirginia  15.1

##### <font color="brown">Example 1b: State populations and debt by year</font>

In [8]:
popdf['debt'] = Series([1.2,1.2,1.1,0.9,1.2])
popdf

state  year  pop  debt
0   Arizona  2005  5.9   1.2
1   Arizona  2010  6.6   1.2
2   Arizona  2015  6.8   1.1
3  Virginia  2010  7.9   0.9
4  Virginia  2015  8.3   1.2

In [9]:
popdf.groupby('year').sum().reset_index()

year            state   pop  debt
0  2005          Arizona   5.9   1.2
1  2010  ArizonaVirginia  14.5   2.1
2  2015  ArizonaVirginia  15.1   2.3

**Group sum is computed for both numeric columns**

##### <font color="brown">Example 2a: School graduates by year</font>

In [10]:
grads = pd.read_csv(open('graduates.csv'))
grads

Student School  Graduating Year       Major
0         Rutgers             2012          CS
1      Penn State             2011          EE
2       Princeton             2013  Psychology
3             MIT             2010     Physics
4         Rutgers             2018        Math
5      Penn State             2019   Economics
6             MIT             2017          CS
7      Penn State             2015     Biology
8         Rutgers             2013  Philosophy
9       Princeton             2012   Economics
10        Rutgers             2015   Economics
11      Princeton             2018          CS
12     Penn State             2015   Economics
13           Yale             2012          CS
14        Rutgers             2013  Psychology

**Q. How many grads in 2012?**

In [11]:
gdf = grads.groupby('Graduating Year').count()
gdf

Student School  Major
Graduating Year                       
2010                          1      1
2011                          1      1
2012                          3      3
2013                          3      3
2015                          3      3
2017                          1      1
2018                          2      2
2019                          1      1

**The count function applied to each group**

In [12]:
gdf.loc[2012]['Major']

3

In [13]:
# one shot
grads.groupby('Graduating Year').count().loc[2012]['Major']

3

##### <font color="brown">Example 2b: School graduates by major, and within each major, by year</font>

**Q. How many Econ grads in 2105?**

**2-level grouping, first by major, then by graduating year within major**

In [14]:
gdf2 = grads.groupby(['Major','Graduating Year']).count()
gdf2

Student School
Major      Graduating Year                
Biology    2015                          1
CS         2012                          2
           2017                          1
           2018                          1
EE         2011                          1
Economics  2012                          1
           2015                          2
           2019                          1
Math       2018                          1
Philosophy 2013                          1
Physics    2010                          1
Psychology 2013                          2

In [15]:
gdf2.loc['Economics',2015]  # note the 2-level indexing

Student School    2
Name: (Economics, 2015), dtype: int64

In [16]:
gdf2.loc['Economics']

Student School
Graduating Year                
2012                          1
2015                          2
2019                          1

In [17]:
type(gdf2.loc['Economics',2015])

pandas.core.series.Series

In [18]:
gdf2.loc['Economics',2015]['Student School']

2

In [19]:
gdf2_reset = gdf2.reset_index()
gdf2_reset

Major  Graduating Year  Student School
0      Biology             2015               1
1           CS             2012               2
2           CS             2017               1
3           CS             2018               1
4           EE             2011               1
5    Economics             2012               1
6    Economics             2015               2
7    Economics             2019               1
8         Math             2018               1
9   Philosophy             2013               1
10     Physics             2010               1
11  Psychology             2013               2

In [20]:
gdf2_reset[(gdf2_reset['Major'] == 'Economics') & (gdf2_reset['Graduating Year'] == 2015)]

Major  Graduating Year  Student School
6  Economics             2015               2

In [21]:
ser = gdf2_reset[(gdf2_reset['Major'] == 'Economics') & (gdf2_reset['Graduating Year'] == 2015)]['Student School']
ser

6    2
Name: Student School, dtype: int64

In [22]:
ser.values[0]

2

##### <font color="brown">Example 2c: Value Counts</font>

**Q. What are the top majors by number of graduates?**

In [23]:
grads

Student School  Graduating Year       Major
0         Rutgers             2012          CS
1      Penn State             2011          EE
2       Princeton             2013  Psychology
3             MIT             2010     Physics
4         Rutgers             2018        Math
5      Penn State             2019   Economics
6             MIT             2017          CS
7      Penn State             2015     Biology
8         Rutgers             2013  Philosophy
9       Princeton             2012   Economics
10        Rutgers             2015   Economics
11      Princeton             2018          CS
12     Penn State             2015   Economics
13           Yale             2012          CS
14        Rutgers             2013  Psychology

In [24]:
major_counts = grads['Major'].value_counts()
major_counts

Major
CS            4
Economics     4
Psychology    2
EE            1
Physics       1
Math          1
Biology       1
Philosophy    1
Name: count, dtype: int64

In [25]:
major_counts[major_counts == major_counts.max()]

Major
CS           4
Economics    4
Name: count, dtype: int64

In [26]:
major_counts[major_counts == major_counts.max()].index.tolist()

['CS', 'Economics']

**Note above that an index can be converted to a list with the tolist method**