## CS 210 Spring 2024 - Mar 7
### NumPy

---

In [2]:
import numpy as np

#### <font color='brown'>Some binary ufuncs</font>

In [3]:
# raise elements of first array to elements of second array
arr1 = [1,2,3,4]
arr2 = [2,1,2,3]
np.power(arr1,arr2)

array([ 1,  2,  9, 64])

In [4]:
powers = np.ones((3,3));
powers[0] = powers[0]*2
powers[2] = powers[2]*3
powers

array([[2., 2., 2.],
       [1., 1., 1.],
       [3., 3., 3.]])

In [5]:
powers = powers.astype(int)
powers

array([[2, 2, 2],
       [1, 1, 1],
       [3, 3, 3]])

In [6]:
arr2d = np.arange(1,10).reshape(3,3)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.power(arr2d,powers)

array([[  1,   4,   9],
       [  4,   5,   6],
       [343, 512, 729]])

In [8]:
# element-wise maximum
print(arr1)
print(arr2)
np.maximum(arr1,arr2)

[1, 2, 3, 4]
[2, 1, 2, 3]


array([2, 2, 3, 4])

In [9]:
arr = np.array([1,2,np.nan,4,5])
print(arr)
arr3 = [3,5,1,15,7]
print(arr3)

[ 1.  2. nan  4.  5.]
[3, 5, 1, 15, 7]


In [10]:
np.maximum(arr3,arr)

array([ 3.,  5., nan, 15.,  7.])

**Above shows that if either of the numbers is NaN, max is NaN**

In [11]:
np.max(arr3,arr)  # max is not binary unfunc

TypeError: only integer scalar arrays can be converted to a scalar index

In [12]:
np.max(arr3)  

15

---

In [13]:
arr3 = [3,5,1,15,7]
print(arr3)

[3, 5, 1, 15, 7]


In [14]:
np.max(arr3,0)  # max is not binary unfunc, second arg for max is "axis"

15

**The binary ufunc name (maximum) is different from unary ufunc name (max) because the 2nd argument has a different meaning from one to the other**

In [15]:
arr2d = np.arange(1,10).reshape(3,3)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
print(np.max(arr2d, 1))  # maximums for each of the rows (across columns), dimension/axis argument is 1

[3 6 9]


In [17]:
print(np.max(arr2d, 0))  # maximums for each of the columns (down rows), dimension/axis argument is 0

[7 8 9]


In [18]:
arr = np.array([1,2,np.nan,4,5])
arr

array([ 1.,  2., nan,  4.,  5.])

**fmax is a universal function (ufunc) that works like maximum, difference is it ignores NaN**

In [19]:
print(arr3)
print(arr)

[3, 5, 1, 15, 7]
[ 1.  2. nan  4.  5.]


In [20]:
np.maximum(arr3,arr)

array([ 3.,  5., nan, 15.,  7.])

In [21]:
np.fmax(arr3,arr)   

array([ 3.,  5.,  1., 15.,  7.])

**greater ufunc**

In [22]:
arr1 = [1,2,3,4]
arr2 = [2,1,2,3]
np.greater(arr1,arr2)  

array([False,  True,  True,  True])

In [23]:
arr, arr3

(array([ 1.,  2., nan,  4.,  5.]), [3, 5, 1, 15, 7])

In [24]:
np.greater(arr,arr3)

array([False, False, False, False, False])

In [25]:
np.greater(arr3,arr)

array([ True,  True, False,  True,  True])

**when using greater, comparing with nan always gives False**

---

#### <font color="brown">Using NumPy random module</font>

**randint function**

In [26]:
np.random.randint(-50,0)  
# single random integer between -50 (inclusive) and 0 (exclusive)

-44

In [27]:
# same as basic Python random.randint except in basic Python random.randint, 2nd arg is inclusive
import random
random.randint(-50,0)

-21

In [28]:
np.random.randint(1,100,5)  
# 5 random integers between 1 (inclusive) and 100 (exclusive)

array([71, 21, 61, 59, 20])

In [29]:
np.random.randint(1,100,(2,3))  
# fill (2,3) array with random integers in range 1..99

array([[83, 10, 93],
       [78,  9, 29]])

**random function**

In [30]:
np.random.random(5)  # 5 random reals 0 (inclusive) thru 1 (exclusive)

array([0.45346068, 0.16830792, 0.36653706, 0.14667739, 0.98695067])

In [31]:
# basic Python version returns a single random number in the range [0,1)
random.random()

0.9393498479769418

In [32]:
np.random.random((3,2)) * 5

array([[4.28491633, 2.00626298],
       [0.4065651 , 3.65314617],
       [1.56713043, 4.22543103]])

**choice function**

In [33]:
nlst = [1,5,3,2,19,12,22,18,75,2,-10,0,15]
np.random.choice(nlst,3)  # 3 random selections from nlst

array([-10,  75,   5])

In [34]:
# Python random.choice gives a single item
random.choice(nlst)  

2

In [35]:
# you can use choice with ndarrays as well
arr = np.array([1,5,3,2,19,12,22,18,75,2,-10,0,15])
np.random.choice(arr,3)

array([ 1,  2, 15])

In [36]:
arr2d = np.arange(1,10).reshape(3,3)
np.random.choice(arr2d,4)

ValueError: a must be 1-dimensional

**random.choice() only works with 1-d arrays**

In [37]:
np.random.choice(nlst,size=8,replace=False)   # no duplicates

array([  5, -10,  22,   3,   2,   1,  75,   2])

**You see two instances of 2 in the result because there were 2 instances in nlst**

In [38]:
nlst

[1, 5, 3, 2, 19, 12, 22, 18, 75, 2, -10, 0, 15]

**shuffle function**

In [39]:
arrs = np.arange(1,10)
arrs

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
np.random.shuffle(arrs)
arrs

array([5, 4, 9, 8, 2, 6, 3, 1, 7])

**<font color="red">Note: shuffle changes the original array</font>**

In [41]:
arrs2d = np.random.randint(1,50,(3,4))
arrs2d

array([[26, 10, 45, 11],
       [44,  1,  5, 38],
       [12, 48, 16, 39]])

In [42]:
np.random.shuffle(arrs2d)  # only shuffles rows 
arrs2d

array([[26, 10, 45, 11],
       [12, 48, 16, 39],
       [44,  1,  5, 38]])

**<font color="red">shuffle only shuffles the rows (in general, only shuffles 1st axis of a multidimensional array)</font>**

In [43]:
arr3d = np.arange(18).reshape(3,3,2)
print(arr3d)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]


In [44]:
np.random.shuffle(arr3d)
arr3d

array([[[12, 13],
        [14, 15],
        [16, 17]],

       [[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

**permutation function**

In [45]:
arrp = np.arange(1,10)
np.random.permutation(arrp)

array([3, 4, 6, 2, 1, 7, 5, 8, 9])

In [46]:
arrp

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

**<font color="red">Note that permutation does NOT change the original array</font>**

In [47]:
arrp2d = np.random.randint(1,50,(5,3))
arrp2d

array([[30, 29, 42],
       [25, 18, 28],
       [ 6,  7, 25],
       [ 1,  8,  8],
       [40, 49,  9]])

In [48]:
np.random.permutation(arrp2d)  # only permutes rows

array([[ 6,  7, 25],
       [25, 18, 28],
       [30, 29, 42],
       [ 1,  8,  8],
       [40, 49,  9]])

**<font color="red">Like shuffle, permutation only permutes the rows (in general, only permutes 1st axis of a multidimensional array)</font>**

In [49]:
arrp2d  # original not changed

array([[30, 29, 42],
       [25, 18, 28],
       [ 6,  7, 25],
       [ 1,  8,  8],
       [40, 49,  9]])

---

#### <font color="brown">NumPy math and stats functions ("reductions")</font>
**functions min, max, mean, sum, std, cumsum**

In [50]:
arrx = np.random.randint(1,20,5)
print(arrx)
print(arrx.max())  
print(arrx.min())
print(arrx.mean())
print(arrx.sum())
print(arrx.std())
print(arrx.cumsum())

[17 13  1  9 18]
18
1
11.6
58
6.1838499334961226
[17 30 31 40 58]


In [51]:
# Alternatively, can use same-named np functions instead of ndarray methods
print(arrx)
print(np.max(arrx))  
print(np.min(arrx))
print(np.mean(arrx))
print(np.sum(arrx))
print(np.std(arrx))
print(np.cumsum(arrx))

[17 13  1  9 18]
18
1
11.6
58
6.1838499334961226
[17 30 31 40 58]


**functions argmax, argmin**

In [52]:
narr = np.array([3,1,-10,5,2,0,-10])
narr

array([  3,   1, -10,   5,   2,   0, -10])

In [53]:
# index of minimum value
print(narr.argmin())  # ndarray method
print(np.argmin(narr))  # np function

2
2


**<font color="red">Using axis for reductions on rows only or columns only</font>**

In [54]:
arr2d = np.arange(1,10).reshape(3,3)[[1,0,2]][:,[1,2,0]]
arr2d

array([[5, 6, 4],
       [2, 3, 1],
       [8, 9, 7]])

In [55]:
# ndarray method versions
print('max in each column: ',end='')
print(arr2d.max(axis=0))
print('row index of max in each column: ',end='')
print(arr2d.argmax(axis=0))
print('max in each row: ',end='')
print(arr2d.max(axis=1))
print('column index of max in each row: ',end='')
print(arr2d.argmax(axis=1))
print()
print('min in each column: ',end='')
print(arr2d.min(axis=0))
print('row index of min in each column: ',end='')
print(arr2d.argmin(axis=0))
print('min in each row: ',end='')
print(arr2d.min(axis=1))
print('column index of min in each row: ',end='')
print(arr2d.argmin(axis=1))

max in each column: [8 9 7]
row index of max in each column: [2 2 2]
max in each row: [6 3 9]
column index of max in each row: [1 1 1]

min in each column: [2 3 1]
row index of min in each column: [1 1 1]
min in each row: [4 1 7]
column index of min in each row: [2 2 2]


In [56]:
# np function versions
print('max in each column: ',end='')
print(np.max(arr2d,axis=0))
print('row index of max in each column: ',end='')
print(np.argmax(arr2d,axis=0))
print('max in each row: ',end='')
print(np.max(arr2d,axis=1))
print('column index of max in each row: ',end='')
print(np.argmax(arr2d,axis=1))

max in each column: [8 9 7]
row index of max in each column: [2 2 2]
max in each row: [6 3 9]
column index of max in each row: [1 1 1]


**<font color="red">Without axis argument, functions apply to entire 2d array<font>**

In [57]:
arr2d

array([[5, 6, 4],
       [2, 3, 1],
       [8, 9, 7]])

In [58]:
arr2d.mean()

5.0

In [59]:
arr2d.mean(axis=1)  # mean of column values for each row

array([5., 2., 8.])

In [60]:
arr2d.mean(axis=0)  # mean of row values for each column

array([5., 6., 4.])

In [61]:
arr2d.cumsum(axis=0)  # cumulative sum for each column

array([[ 5,  6,  4],
       [ 7,  9,  5],
       [15, 18, 12]])

---

#### <font color="brown">Unique</font>

In [62]:
scores = np.array([10,9,9,8,2,3,2,7,5,8])
np.unique(scores)   

array([ 2,  3,  5,  7,  8,  9, 10])

**unique gives <font color="red">sorted</font> list of unique values**

In [63]:
arr = [[ 3,  3,  9],
       [10, 12,  1],
       [ 9,  8,  4],
       [ 2,  3, 12]]

In [64]:
np.unique(arr)

array([ 1,  2,  3,  4,  8,  9, 10, 12])

---

#### <font color="brown">Sorting</font>

In [65]:
a = np.array([3,-1,2,5,15,22,-10,85])
print(a)

[  3  -1   2   5  15  22 -10  85]


**np sort function**

In [66]:
np.sort(a)

array([-10,  -1,   2,   3,   5,  15,  22,  85])

In [67]:
print(a) 

[  3  -1   2   5  15  22 -10  85]


**<font color="red">Note that sort function does not change the original array</font>**

**ndarray sort method**

In [68]:
a.sort()  
print(a)

[-10  -1   2   3   5  15  22  85]


**<font color="red">Note that ndarray sort method changes the original array</font>**

In [69]:
a = np.array([3,-1,2,5,15,22,-10,85])
print(a)

[  3  -1   2   5  15  22 -10  85]


**np argsort function**

In [70]:
# positions of sorted values
sort_ix = np.argsort(a)
print(np.sort(a))
print(sort_ix)

[-10  -1   2   3   5  15  22  85]
[6 1 2 0 3 4 5 7]


**ndarray argsort method**

In [71]:
print(a.argsort())

[6 1 2 0 3 4 5 7]


**sort on 2D array**

In [72]:
a = [3,-1,2,5,15,22,-10,85]
b = [9,2,15,10,1,3,-2,5]
c = np.array([a,b])
print(c)

[[  3  -1   2   5  15  22 -10  85]
 [  9   2  15  10   1   3  -2   5]]


In [73]:
np.sort(c)

array([[-10,  -1,   2,   3,   5,  15,  22,  85],
       [ -2,   1,   2,   3,   5,   9,  10,  15]])

**<font color="red">Note that each row is individually sorted</font>**

In [74]:
np.argsort(c)  

array([[6, 1, 2, 0, 3, 4, 5, 7],
       [6, 4, 1, 5, 7, 0, 3, 2]])

In [75]:
np.argsort(c)[:,-3:]  # positions of max 3 values in each row

array([[4, 5, 7],
       [0, 3, 2]])

In [76]:
arr = np.random.randint(1,13,(4,3))
print(arr)

[[ 2 12  2]
 [ 7  5  4]
 [ 1 11  5]
 [11 11 11]]


In [77]:
np.sort(arr,axis=0)   # sort along columns

array([[ 1,  5,  2],
       [ 2, 11,  4],
       [ 7, 11,  5],
       [11, 12, 11]])

In [78]:
np.argsort(arr,axis=0)

array([[2, 1, 0],
       [0, 2, 1],
       [1, 3, 2],
       [3, 0, 3]])

In [79]:
np.sort(arr,axis=1)  # sort each row

array([[ 2,  2, 12],
       [ 4,  5,  7],
       [ 1,  5, 11],
       [11, 11, 11]])

In [80]:
np.sort(arr)  # axis=1 is default

array([[ 2,  2, 12],
       [ 4,  5,  7],
       [ 1,  5, 11],
       [11, 11, 11]])

---

#### <font color="brown">where function</font>

In [81]:
xlst = [1,2,3,4,5]
ylst = [6,7,8,9,10]
condlst = [True, False, True, True, False]

In [82]:
# want value from xarr if cond is True, otherwise value from yarr
res = [x if c else y
           for x,y,c in zip(xlst, ylst, condlst)]
res

[1, 7, 3, 4, 10]

**Using where function to conditionally manipulate items of array**

In [83]:
# above list comprehension is equivalent to this
np.where(condlst, xlst, ylst)

array([ 1,  7,  3,  4, 10])

**Either or both of 2nd and 3rd arguments to np.where can be scalars**

In [84]:
arr = np.random.randint(-5,5,(4,4))
print(arr,'\n')

# replace all negative values with -1 and other values with 1
arrx = np.where(arr < 0, -1, 1)
print(arrx)

[[-5 -1 -2 -4]
 [ 2  1  3  2]
 [-5  3 -4  2]
 [-5  4  2  4]] 

[[-1 -1 -1 -1]
 [ 1  1  1  1]
 [-1  1 -1  1]
 [-1  1  1  1]]


In [85]:
# replace only negative values with -1
arrx = np.where(arr < 0, -1, arr)
print(arrx)

[[-1 -1 -1 -1]
 [ 2  1  3  2]
 [-1  3 -1  2]
 [-1  4  2  4]]
