## CS 210 Spring 2024 - Mar 4
### NumPy

In [1]:
import numpy as np

---

#### <font color="brown">Type Casting</font>

##### You can CAST an array from one dtype to another using astype method.<br>Using astype ALWAYS CREATES A NEW ARRAY, leaving the original array untouched

In [2]:
floatarr = np.array([1,2.5,3])
floatarr.dtype

dtype('float64')

In [3]:
intarr = floatarr.astype(np.int64)
intarr, intarr.dtype

(array([1, 2, 3]), dtype('int64'))

In [4]:
# or, can just say int instead of np.int64
intarr2 = floatarr.astype(int)
intarr2, intarr2.dtype

(array([1, 2, 3]), dtype('int64'))

**Can parse strings that represent numeric values into numeric type**

In [8]:
num_strings = np.array(['1.5', '3.6', '-2.9'])
narr = num_strings.astype(float)  # parse each item as a real number
narr, narr.dtype

(array([ 1.5,  3.6, -2.9]), dtype('float64'))

**Only if the string actually does represent a numeric value**

In [9]:
np.array(['1.2','2.5','x.y']).astype(float)

ValueError: could not convert string to float: 'x.y'

In [10]:
# assign another array's dtype to intarr
farr = intarr.astype(floatarr.dtype) 
farr, intarr

(array([1., 2., 3.]), array([1, 2, 3]))

---

#### <font color="brown">Array-array and array-scalar operations</font>

##### Batch operations applied to arrays as a whole is called <em>vectorization</em>

In [11]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
arr * arr  # corresponding elements are multiplied

array([[ 1,  4,  9],
       [16, 25, 36]])

In [13]:
arr + arr  # corresponding elements are added

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [14]:
1/arr  # invert each element

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [15]:
arr ** 2  # square each element

array([[ 1,  4,  9],
       [16, 25, 36]])

In [16]:
np.power(arr,2)

array([[ 1,  4,  9],
       [16, 25, 36]])

---

#### <font color="brown">Indexing and Slicing</font>

##### 1D Array

In [17]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr[5:8]

array([5, 6, 7])

In [19]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [20]:
arr[:-2]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [21]:
arr[-3:]

array([7, 8, 9])

In [22]:
arr[3:-5]

array([3, 4])

**<font color="red">A slice on a 1D array is a "view" (not copy) on original array. If you modify a slice, the original array is modified!!</font>**

In [23]:
arr_slice = arr[5:8]
arr_slice

array([5, 6, 7])

In [24]:
arr_slice[1] = 66  
arr  

array([ 0,  1,  2,  3,  4,  5, 66,  7,  8,  9])

**Modification to the slice reflects in the original!**

In [25]:
arr[5:8][1] = 6  # 2nd element of the slice
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
arr[5:8] = 10  # every slice item is set to 10
arr

array([ 0,  1,  2,  3,  4, 10, 10, 10,  8,  9])

In [27]:
# remember, arr_slice is a view on the original, so it reflects change as well
arr_slice  

array([10, 10, 10])

In [28]:
arr_slice[:] = 13 # every slice item is set to 13
arr

array([ 0,  1,  2,  3,  4, 13, 13, 13,  8,  9])

**You can make a copy of a slice by using copy method**

In [29]:
slice_copy = arr[5:8].copy()  # explicit copy of slice, not a view
slice_copy[1] = 66
print(arr)
print(slice_copy)

[ 0  1  2  3  4 13 13 13  8  9]
[13 66 13]


---

##### 2D Array

In [30]:
myarr = np.arange(1,10).reshape(3,3)
myarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
myarr[1]  # second row

array([4, 5, 6])

In [32]:
myarr[:,2]  # third column

array([3, 6, 9])

In [33]:
# 1st and 3rd rows
myarr[[0,2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [34]:
# can also be written like this
myarr[[-3,-1]]

array([[1, 2, 3],
       [7, 8, 9]])

In [35]:
# 1st and 3rd columns
myarr[:,[0,2]]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [36]:
myarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
# shuffle rows
myarr[[2,0,1]]

array([[7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])

**The original array is unchanged**

In [38]:
myarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
# shuffle columns
myarr[:,[2,0,1]]

array([[3, 1, 2],
       [6, 4, 5],
       [9, 7, 8]])

In [40]:
myarr[1] = [-1,-2,-3]  # update 2nd row
myarr

array([[ 1,  2,  3],
       [-1, -2, -3],
       [ 7,  8,  9]])

In [41]:
myarr[:,2] = [2,1,0]   # update 3rd column
myarr

array([[ 1,  2,  2],
       [-1, -2,  1],
       [ 7,  8,  0]])

In [42]:
myarr[:,2] = -1   # set all items of 3rd column to same value
myarr

array([[ 1,  2, -1],
       [-1, -2, -1],
       [ 7,  8, -1]])

**Row and columns index lists**

In [43]:
narr = np.arange(32).reshape(8,4)
narr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [44]:
narr[[2,4,0,7],[1,2,0,3]]  # selects [2,1],[4,2],[0,0],[7,3]

array([ 9, 18,  0, 31])

In [45]:
narr[[2,4,0,7]]  # rows as specified

array([[ 8,  9, 10, 11],
       [16, 17, 18, 19],
       [ 0,  1,  2,  3],
       [28, 29, 30, 31]])

In [46]:
narr[[2,4,0,7]][:,[1,2,3,0]]  # shuffle columns

array([[ 9, 10, 11,  8],
       [17, 18, 19, 16],
       [ 1,  2,  3,  0],
       [29, 30, 31, 28]])

In [47]:
# above is equivalent to
narr_subrows = narr[[2,4,0,7]]
print(narr_subrows,'\n')
narr_subrows_shuffle = narr_subrows[:,[1,2,3,0]]
print(narr_subrows_shuffle)

[[ 8  9 10 11]
 [16 17 18 19]
 [ 0  1  2  3]
 [28 29 30 31]] 

[[ 9 10 11  8]
 [17 18 19 16]
 [ 1  2  3  0]
 [29 30 31 28]]


**Modifying row slice**

In [48]:
arr2d = np.arange(1,10).reshape(3,3)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
rowslc = arr2d[1:]    # same as arr2d[[1,2]]
rowslc

array([[4, 5, 6],
       [7, 8, 9]])

In [50]:
rowslc[0] = 10
rowslc

array([[10, 10, 10],
       [ 7,  8,  9]])

In [51]:
arr2d  # original array is modified!

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

**<font color="red">Above shows that slicing by row gives a VIEW, not a copy</font>**

**But using a row list to get a "slice" works differently**

In [52]:
rowslc2 = arr2d[[1,2]]
rowslc2

array([[10, 10, 10],
       [ 7,  8,  9]])

In [53]:
rowslc2[0] = 5
rowslc2

array([[5, 5, 5],
       [7, 8, 9]])

In [54]:
arr2d

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

**Using a row list to extract a subset of rows is NOT a "slice" in that sense that it gives a copy not a view, so modifying it does not affect the source array**

**Modifying column slice**

In [55]:
arr2d = np.arange(1,10).reshape(3,3)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
colslc = arr2d[:, 1:]  # 2nd and 3rd columns
colslc

array([[2, 3],
       [5, 6],
       [8, 9]])

In [57]:
colslc[1] = -1
colslc

array([[ 2,  3],
       [-1, -1],
       [ 8,  9]])

In [58]:
arr2d

array([[ 1,  2,  3],
       [ 4, -1, -1],
       [ 7,  8,  9]])

**<font color="red">Just like slicing by row, slicing by column also gives a VIEW, not a copy</font>**

**But using a column list to extract a subset of columns is NOT a "slice" in that sense that it gives a copy not a view, so modifying it does not affect the source array**

In [59]:
arr2d = np.arange(1,10).reshape(3,3)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
colslc = arr2d[:, [0,2]]  # 1st and 3rd columns
colslc

array([[1, 3],
       [4, 6],
       [7, 9]])

In [61]:
colslc[:,1] = 10  # assign 10 to second column of slice
colslc

array([[ 1, 10],
       [ 4, 10],
       [ 7, 10]])

In [62]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**No change to source array**

---

#### <font color="brown">Slicing using a boolean filter (mask)</font>

In [63]:
arr=np.arange(9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [64]:
slc = arr[arr > 4]  # pick elements > 4
slc

array([5, 6, 7, 8])

In [65]:
# basically what you are doing is making a boolean filter array, then applying it on arr
filter = arr > 4
filter

array([False, False, False, False, False,  True,  True,  True,  True])

In [66]:
slc = arr[filter]
slc

array([5, 6, 7, 8])

In [67]:
slc[0] = 10
slc

array([10,  6,  7,  8])

In [68]:
arr  # original is not modified

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

**<font color="red">Slicing with boolean filtering gives a COPY, not a view</font>**

In [69]:
arr2d = np.arange(1,13).reshape(4,3)
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [70]:
arr2d_slc = arr2d[[True,False,True,True]] # get all but 2nd row
print(arr2d_slc)

[[ 1  2  3]
 [ 7  8  9]
 [10 11 12]]


In [71]:
arr2d_slc[0] = 0  # change 1st row to all zeros
arr2d_slc

array([[ 0,  0,  0],
       [ 7,  8,  9],
       [10, 11, 12]])

In [72]:
arr2d   # unchanged

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [73]:
arr2d[[i%2 == 0 for i in range(4)]]  # even indexed rows

array([[1, 2, 3],
       [7, 8, 9]])

**Applying a boolean mask from one array to another**

In [74]:
numarr = np.array([2,5,4,12])
arr2d[(numarr % 2 == 0)]   # basically arr2d[[True,False,True,False]]

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [10, 11, 12]])

In [75]:
arr2d[~(numarr % 2 == 0)]  # negation, gets only the 2nd row of arr2d

array([[4, 5, 6]])

In [76]:
arr2d[(numarr % 2 == 0),0]  # only the 1st column of selected rows

array([ 1,  7, 10])

In [77]:
mask = (numarr < 3) | (numarr > 10)
mask

array([ True, False, False,  True])

In [78]:
arr2d[mask]  # first and last rows

array([[ 1,  2,  3],
       [10, 11, 12]])

In [79]:
arr2dcopy = arr2d.copy()
arr2dcopy[arr2dcopy > 6] = 0  # set all values > 6 to 0
arr2dcopy

array([[1, 2, 3],
       [4, 5, 6],
       [0, 0, 0],
       [0, 0, 0]])

In [80]:
arr2dcopy = arr2d.copy()
arr2dcopy[(arr2dcopy < 3) | (arr2dcopy > 6)] = -1  
arr2dcopy

array([[-1, -1,  3],
       [ 4,  5,  6],
       [-1, -1, -1],
       [-1, -1, -1]])

**Global filtering with any and all**

In [81]:
arr = np.array([0,1,-5,2,9,0,3,-4,6])
print(arr.any())   

True


*0 is False, non-zero is True*

In [82]:
np.zeros(9).any()

False

In [83]:
arr.all()

False

In [84]:
np.ones(9).all()

True

---

#### Universal Function, or ufunc, is a function that performs element-wise operations on ndarrays.<br>Unary ufuncs work on a single ndarry, binary ufuncs work on a pair

---

#### <font color="brown">Some unary ufuncs</font>

In [85]:
arr = np.arange(1,6)
arr

array([1, 2, 3, 4, 5])

In [86]:
np.exp(arr)  # computes e^x for each x in arr

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [87]:
np.square(arr)

array([ 1,  4,  9, 16, 25])

In [88]:
np.sqrt(np.square(arr))

array([1., 2., 3., 4., 5.])

In [89]:
np.power(arr,3)

array([  1,   8,  27,  64, 125])

In [90]:
# same as
arr ** 3

array([  1,   8,  27,  64, 125])

In [91]:
arr2 = np.arange(-3,4)
arr2

array([-3, -2, -1,  0,  1,  2,  3])

In [92]:
np.abs(arr2)

array([3, 2, 1, 0, 1, 2, 3])

In [93]:
np.fabs(arr2)  # same, but gives real numbers, faster than abs

array([3., 2., 1., 0., 1., 2., 3.])

**fabs is faster than abs, so even if you want to abs on an int ndarray, better to do fabs first then cast astype(int)**

In [94]:
np.fabs(arr2).astype(int)

array([3, 2, 1, 0, 1, 2, 3])

In [95]:
arr2d = np.arange(1,10).reshape(3,3)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [96]:
np.square(arr2d)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [97]:
np.power(arr2d,2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [98]:
arr2d   # does not change original array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [99]:
# ceil, floor, round to nearest integer
arr = np.exp(np.arange(1,6))
print(arr)
print(np.ceil(arr))
print(np.floor(arr))
print(np.rint(arr))

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[  3.   8.  21.  55. 149.]
[  2.   7.  20.  54. 148.]
[  3.   7.  20.  55. 148.]


In [100]:
# is nan
arr = np.array([1,2,4,5]) 
print(np.isnan(arr))

[False False False False]


In [101]:
# np.nan gives NaN
arr = np.array([1,2,np.nan,4,5])  # NaN is value used to denote not available, or null
print(np.isnan(arr))

[False False  True False False]
